### ISSUE TITLE
hosting with server?

### ISSUE THREAD

**Issue by ashfaqur** [N-Perry/Meetups#1]
Hi I have a quick question.
Are you hosting on vercel with an actual server?

**Comment by N-Perry** [comment]
> Hi I have a quick question. Are you hosting on vercel with an actual server?

It's been a while since i looked at this project, so I'm a bit rusty on the details. I believe the answer is technically yes.

The Sveltekit app is hosted on a Vercel server, and utilizes a firebase DB for SSR
